name: aws-codeartifact-publish-package-version
description: Creates a new generic package version containing one or more assets (or files).
branding:
  icon: code
  color: blue

inputs:
  package_version:
    description: "Artifact version"
    required: true
  files:
    description: "A single file or a folder that will be published as .gz file"
    required: true 

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        tar -czvf ${{ vars.PACKAGE_NAME }}.tar.gz ${{ inputs.files }}
        export ASSET_SHA256=$(sha256sum ${{ vars.PACKAGE_NAME }}.tar.gz | awk '{print $1;}')
        aws codeartifact publish-package-version --domain ${{ vars.DOMAIN }} --repository ${{ vars.REPOSITORY }} \
          --format ${{ vars.FORMAT }} --namespace ${{ vars.NAMESPACE }} --package ${{ vars.PACKAGE_NAME }} --package-version ${{ inputs.package_version }} \
          --asset-content ${{ vars.PACKAGE_NAME }}.tar.gz --asset-name ${{ vars.PACKAGE_NAME }}.tar.gz \
          --asset-sha256 $ASSET_SHA256 --region ${{ vars.REGION }}
