name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      jira_ref:
        required: false
        type: string
      debug:
        required: false
        type: boolean

    outputs:
      issue_number:
        description: "Created Issue ID"
        value: ${{ jobs.code-build.outputs.issue_number }}

permissions:
  id-token: write  
  contents: read

jobs:
  code-build:
    name: Code-Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      issue_number: ${{ steps.create_issue.outputs.issue-number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
        with:
          ref: ${{ inputs.branch }}           
          
      - name: Run Ant Build
        run: |
          if [[ ${{ inputs.debug }} == "false" ]];
          then
            ant ${{ inputs.ant_target }}
          else
            ant -v ${{ inputs.ant_target }}
          fi
          
          if [ $? -eq 0 ]; then
            echo "✅ ${{ inputs.ant_target }} completed successfully"
          else
            echo "❌ ${{ inputs.ant_target }} failed"
            exit 1
          fi

      - name: Uploading the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: ./build/jar/*

      - name: Checkout automation Repo
        if: ${{ inputs.environment != 'Dev' }}
        uses: actions/checkout@v4
        with:
          repository: dhakshna-learning/ci-cd-automation
          ref: master
          path: ci-cd-automation
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: creating issue for approval
        if: ${{ inputs.environment != 'Dev' }}
        uses: dhakshna-learning/ci-cd-automation/.github/actions/create-issues@master
        id: create_issue
        with:
          mode: "create"
          issue-title: "[${{ inputs.jira_ref }}] Approval needed for deploying to ${{ inputs.environment }} environment"
          issue-body: |
            Hi Team,

            The build for the `${{ inputs.environment }}` environment has completed successfully. 

            Please review and approve the deployment to proceed.

            https://dcloudsystems.atlassian.net/browse/${{ inputs.jira_ref }}

            Thanks,
            DevOps Team
          approvers: ${{ needs.Initialising.outputs.devops_ids }}
          secret: ${{ secrets.PEM_KEY }}
