name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write  
  contents: read
  issues: write

jobs:
  CI-secrets-Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      issue_number: ${{ steps.create_issue.outputs.issue_number }}
      run_number: ${{ github.run_number }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Run Ant Build
        run: |
          ant ${{ inputs.ant_target }}

          if [ $? -eq 0 ]; then
            echo "✅ ${{ inputs.ant_target }} completed successfully"
          else
            echo "❌ ${{ inputs.ant_target }} failed"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: ./build/jar/*

      - name: Create deployment approval issue
        uses: JasonEtco/create-an-issue@v2.6.0
        id: create_issue
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUNNUMBER: ${{ github.run_number  }}
        with:
          filename: .github/deployment-approval.md

    outputs:
      approval_issue_number: ${{ steps.create_issue.outputs.issue-number }}
