name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: false
        type: string
        default: build
      java_home:
        required: true
        type: string
      ant_home:
        required: true
        type: string

jobs:
  ant-build:
    runs-on: CICD
    env:
      JAVA_HOME: ${{ inputs.java_home }}
      ANT_HOME: ${{ inputs.ant_home }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PATH
        run: |
          echo "${JAVA_HOME}/bin" >> $GITHUB_PATH
          echo "${ANT_HOME}/bin" >> $GITHUB_PATH

      - name: Setup tools
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          echo "ANT_HOME=$ANT_HOME"
          ant -version

      - name: Run Ant Build
        run: ant ${{ inputs.ant_target }}
