name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: false
        type: string

jobs:
  CI-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ant Build
        run: |
          ant ${{ inputs.ant_target }}

          if [ $? -eq 0 ]; then
            echo "✅ ${{ inputs.ant_target }} completed successfully"
          else
            echo "❌ ${{ inputs.ant_target }} failed"
          fi
        
