name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: false
        type: string
        default: build
      java_home:
        required: true
        type: string
        default: build
      ant_home:
        required: true
        type: string
        default: build

jobs:
  ant-build:
    runs-on: CICD
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tools
        run: |
              export JAVA_HOME=${{ inputs.java_home }}
              export ANT_HOME=${{ inputs.ant_home }}
              export PATH=${PATH}:${JAVA_HOME}/bin:${ANT_HOME}/bin
              java -version
              ant -version

      - name: Run Ant Build
        run: ant ${{ inputs.ant_target }}
