name: Deploy on Approval

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      issue_number:
        required: true
        type: number
      run_number:
        required: true
        type: number

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: CI Build Pipeline.yml     # Match your workflow filename exactly
          repo: dhakshna-learning/ci-cd-automation
          run_number: ${{ inputs.run_number }}
          name: Build-Artifacts
          path: ${{ github.workspace }}

      - name: Deploy to ${{ inputs.environment }}
        run: echo "Simulating deployment to ${{ inputs.environment }}"

      - name: Close Approval Issue
        uses: peter-evans/close-issue@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.issue_number }}
          comment: 'Deployment Completed 🌟'
