name: Snyk Scan Artifacts
on:
   workflow_call: 
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

permissions:
    id-token: write
    contents: read  
   
jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          
      - name: Install Snyk CLI
        run: |
           npm install -g snyk
           snyk --version
           
      - name: Run Snyk scan to find code vulnerabilities
        if: ${{ inputs.environment == 'Dev' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --all-projects --policy-path=./.snyk
        continue-on-error: true

      - name: Run Snyk scan to find code vulnerabilities on ${{ inputs.branch }}
        if: ${{ inputs.environment != 'Dev' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --all-projects --policy-path=./.snyk
