name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write  
  contents: read

jobs:
  CI-secrets-Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Debug Vars
        run: |
          echo "REGION=${{ vars.REGION }}"
          echo "OIDC=${{ secrets.OIDC_ARN }}"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Run Ant Build
        run: |
          ant ${{ inputs.ant_target }}

          if [ $? -eq 0 ]; then
            echo "✅ ${{ inputs.ant_target }} completed successfully"
          else
            echo "❌ ${{ inputs.ant_target }} failed"
          fi

      # - name: Writing the test
      #   run: |
      #     echo "Deploying to instance: ${{ secrets.HOST }}"
      #     aws ssm send-command \
      #       --document-name "AWS-RunShellScript" \
      #       --targets "Key=InstanceIds,Values=${{ secrets.HOST }}" \
      #       --parameters 'commands=["echo HELLO >> /tmp/test.txt"]'

      - name: Passing the artifact to next job
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: ./build/jar/*
