name: CI Build Pipeline

on:
  workflow_call:
    inputs:
      ant_target:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write  
  contents: read

jobs:
  CI-secrets-Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Debug Vars
        run: |
          echo "REGION=${{ vars.REGION }}"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Deploying the application
        run: |
          echo "Deploying to instance: ${{ secrets.HOST }}"
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=${{ secrets.HOST }}" \
            --parameters 'commands=["echo HELLO >> /tmp/test.txt"]'
