name: Upload Artifact to CodeArtifact

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write  
  contents: read

jobs:
  Upload-Artifact:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Debug Vars
        run: |
          echo "REGION=${{ vars.REGION }}"
          echo "OIDC=${{ secrets.OIDC_ARN }}"
          
      - name: Checkout github actions
        uses: actions/checkout@v4
        with:
          repository: dhakshna-learning/ci-cd-automation/.github
          ref: 'master'
          path: github-actions

      - name: Download the artifcats to upload
        uses: actions/download-artifact@v4
        with:
          name: Build-Artifacts

      - name: Set version
        id: set-version
        run: echo VERSION=221 >> $GITHUB_OUTPUT

      # Begin Calling composite action here
      - name: Initiating the Artifact Upload
        id: upload
        uses: ./github-actions/.github/actions/upload-artifact
        with:
          package_version: ${{ steps.set-version.outputs.VERSION }}
          files: ./Build-Artifacts/*.jar
      # End Calling composite action here
